# Guided Project #3 - Ebay Car Sales
By [Luis Munguia](http://www.linkedin.com/in/luis-munguia) and [Dataquest](http://www.dataquest.io)

In this guided project, I'll work with a dataset on car sales from *eBay Kelinanzeigen* (Germany here I go!). This data was scraped and uploaded to Kaggle but here it's been dirtied to closely resemble what I would expect from a scraped dataset. Also, only 50,000 data points were sampled from the full dataset.

The data dictionary is as follows:

* `dateCrawled`: When this ad was first crawled. All field-values are taken from this date.
* `name`: Name of the car.
* `seller`: Whether the seller is private or a dealer.
* `offerType`: The type of listing.
* `price`: The price on the ad to sell the car.
* `abtest`: Whether the listing is included in an A/B test.
* `vehicleType`: The vehicle Type.
* `yearOfRegistration`: The year in which which year the car was first registered.
* `gearbox`: The transmission type.
* `powerPS`: The power of the car in PS.
* `model`: The car model name.
* `kilometer`: How many kilometers the car has driven.
* `monthOfRegistration`: The month in which which year the car was first registered.
* `fuelType`: What type of fuel the car uses.
* `brand`: The brand of the car.
* `notRepairedDamage`: If the car has a damage which is not yet repaired.
* `dateCreated`: The date on which the eBay listing was created.
* `nrOfPictures`: The number of pictures in the ad.
* `postalCode`: The postal code for the location of the vehicle.
* `lastSeenOnline`: When the crawler saw this ad last online.

This project's aim is to clean the data and analyze used car listings.

## 1.- Use pandas and NumPy libraries.

Use pandas to import data from `autos.csv` and display data.

In [1]:
import pandas as pd
import numpy as np

autos = pd.read_csv("autos.csv", encoding = "Latin-1" ) #Unicode failed the fist time (UTF-8)
autos                                                   #Changed to Latin-1

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [2]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

In [3]:
autos.head()

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

Data is not sorted, I'm missing data from 5 columns, and language seems to be deutsch in some cases.

## 2.- Change column names from camelCase to snake_case.

Change column display type and generalize names.

In [4]:
camelCase = autos.columns

In [5]:
camelCase

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [6]:
snake_case = ['date_crawled', 'name', 'seller', 'offer_type', 'price', 'ab_test', 'vehicle_type',
              'registration_year', 'gear_box', 'power_PS', 'model', 'odometer',
              'registration_month', 'fuel_type', 'brand', 'unrepaired_damage', 'ad_created',
              'nr_of_pictures', 'postal_code', 'last_seen']

In [7]:
autos.columns = snake_case

In [8]:
autos.head()

,date_crawled,name,seller,offer_type,price,ab_test,vehicle_type,registration_year,gear_box,power_PS,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

I changed from camelCase to snake_case and modified the name of 4 columns to make them more descriptive.

## 3.- Preliminary Data exploration.

Use `DataFrame.describe()`, `Series.value_counts()` and `Series.head()` to explore data and determine what needs cleaning and what need to be dropped.

In [9]:
autos.describe(include='all')

,date_crawled,name,seller,offer_type,price,ab_test,vehicle_type,registration_year,gear_box,power_PS,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-03-08 10:40:35,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

In [10]:
autos["seller"].value_counts()

privat        49999
gewerblich        1
Name: seller, dtype: int64

In [11]:
autos["offer_type"].value_counts()

Angebot    49999
Gesuch         1
Name: offer_type, dtype: int64

In [12]:
autos["nr_of_pictures"].value_counts()

0    50000
Name: nr_of_pictures, dtype: int64

Change column name "odometer" for "odometer_km".

Erase the following columns: `seller`, `offer_type`, `nr_of_pictures`.

Delete non-numeric values from `price` and `odometer`. Display as floats.

In [13]:
autos.rename(columns={"odometer":"odometer_km"}, inplace = True)
autos.drop(["seller", "offer_type", "nr_of_pictures"], axis = 1, inplace = True)
autos["price"] = autos["price"].str.replace("$","").str.replace(",","").astype(int)
autos["odometer_km"] = autos["odometer_km"].str.replace("km","").str.replace(",","").astype(int)
autos.head()

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gear_box,power_PS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,5000,control,bus,2004,manuell,158,andere,150000,3,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,8500,control,limousine,1997,automatik,286,7er,150000,6,benzin,bmw,nein,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,8990,test,limousine,2009,manuell,102,golf,70000,7,benzin,volkswagen,nein,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,4350,control,kleinwagen,2007,automatik,71,fortwo,70000,6,benzin,smart,nein,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,1350,test,kombi,2003,manuell,0,focus,150000,7,benzin,ford,nein,2016-04-01 00:00:00,39218,2016-04-01 14:38:50

## 4.- Data Analysis for Price and Odometer.

Use `Seriews.unique().shape`, `Series.describe()` and `Series.value_counts()` to explore data and determine if there's outliers that need to be dropped.

In [14]:
autos["price"].unique().shape

(2357,)

In [15]:
autos["price"].describe().apply(lambda x: format(x, 'f')) #Found this lambda to better view info.

count       50000.000000
mean         9840.043760
std        481104.380500
min             0.000000
25%          1100.000000
50%          2950.000000
75%          7200.000000
max      99999999.000000
Name: price, dtype: object

In [16]:
autos["price"].value_counts().sort_index(ascending = True).head(20)

0     1421
1      156
2        3
3        1
5        2
8        1
9        1
10       7
11       2
12       3
13       2
14       1
15       2
17       3
18       1
20       4
25       5
29       1
30       7
35       1
Name: price, dtype: int64

In [17]:
autos["price"].value_counts().sort_index(ascending = False).head(20)

99999999    1
27322222    1
12345678    3
11111111    2
10000000    1
3890000     1
1300000     1
1234566     1
999999      2
999990      1
350000      1
345000      1
299000      1
295000      1
265000      1
259000      1
250000      1
220000      1
198000      1
197000      1
Name: price, dtype: int64

After review, I decided to drop values < than 1,000 because of the first quartile, up to 155,000 because from there up those cars just inflate the statistics.

But after running the code, it seemed I was going to wipe out more than 20% of the data.

I decided to wipe less than 10% of the data so instead of using 1,000 I droped to 200.

In [18]:
(~autos["price"].between(200,155000)).sum() / autos.shape[0] #In this code ~ invert operator selects 
                                                             #everything not between the two numbers

0.04746

In [19]:
autos = autos[autos["price"].between(350,155000)]

In [20]:
autos["price"].describe().apply(lambda x: format(x, 'f'))

count     46395.000000
mean       6067.411143
std        8001.480566
min         350.000000
25%        1400.000000
50%        3300.000000
75%        7750.000000
max      155000.000000
Name: price, dtype: object

In [21]:
autos["odometer_km"].unique().shape

(13,)

In [22]:
autos["odometer_km"].describe()

count     46395.000000
mean     125674.964975
std       39458.683760
min        5000.000000
25%      100000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

In [23]:
autos["odometer_km"].value_counts()

150000    29776
125000     4924
100000     2059
90000      1700
80000      1397
70000      1202
60000      1139
50000      1000
40000       809
30000       769
20000       729
5000        654
10000       237
Name: odometer_km, dtype: int64

There is not much to change in odometer. The values seem to be predefined.

## 5.- Data Analysis for Date Values.

Use `Seriews.unique().shape`, `Series.describe()` and `Series.value_counts()` to explore date values data and understand distributions.

In [24]:
autos[['date_crawled','ad_created','last_seen']][0:5]

          date_crawled           ad_created            last_seen
0  2016-03-26 17:47:46  2016-03-26 00:00:00  2016-04-06 06:45:54
1  2016-04-04 13:38:56  2016-04-04 00:00:00  2016-04-06 14:45:08
2  2016-03-26 18:57:24  2016-03-26 00:00:00  2016-04-06 20:15:37
3  2016-03-12 16:58:10  2016-03-12 00:00:00  2016-03-15 03:16:28
4  2016-04-01 14:38:50  2016-04-01 00:00:00  2016-04-01 14:38:50

There is a function in pandas that lets me select the characters in a column, which can be used to group by days. The goal is to generate the distribution and gain insights on the dates.

In [25]:
autos['date_crawled'].str[:10].value_counts(normalize = True, dropna = False).sort_index()

2016-03-05    0.025455
2016-03-06    0.014096
2016-03-07    0.036211
2016-03-08    0.033064
2016-03-09    0.032870
2016-03-10    0.032396
2016-03-11    0.032784
2016-03-12    0.037159
2016-03-13    0.015605
2016-03-14    0.036405
2016-03-15    0.034185
2016-03-16    0.029529
2016-03-17    0.031361
2016-03-18    0.012825
2016-03-19    0.034486
2016-03-20    0.038151
2016-03-21    0.037633
2016-03-22    0.032956
2016-03-23    0.032353
2016-03-24    0.029076
2016-03-25    0.031275
2016-03-26    0.032417
2016-03-27    0.031102
2016-03-28    0.034896
2016-03-29    0.033754
2016-03-30    0.033646
2016-03-31    0.031900
2016-04-01    0.033861
2016-04-02    0.035672
2016-04-03    0.038603
2016-04-04    0.036642
2016-04-05    0.013105
2016-04-06    0.003147
2016-04-07    0.001379
Name: date_crawled, dtype: float64

According to the above list, data was crawled for the majority of March and the first week of April.

In [26]:
autos['ad_created'].str[:10].value_counts(normalize = True, dropna = False).sort_index()

2015-06-11    0.000022
2015-08-10    0.000022
2015-09-09    0.000022
2015-11-10    0.000022
2015-12-05    0.000022
2015-12-30    0.000022
2016-01-03    0.000022
2016-01-07    0.000022
2016-01-10    0.000043
2016-01-13    0.000022
2016-01-14    0.000022
2016-01-16    0.000022
2016-01-22    0.000022
2016-01-27    0.000065
2016-01-29    0.000022
2016-02-01    0.000022
2016-02-02    0.000043
2016-02-05    0.000043
2016-02-07    0.000022
2016-02-08    0.000022
2016-02-09    0.000022
2016-02-11    0.000022
2016-02-12    0.000043
2016-02-14    0.000043
2016-02-16    0.000022
2016-02-17    0.000022
2016-02-18    0.000043
2016-02-19    0.000065
2016-02-20    0.000043
2016-02-21    0.000065
                ...
2016-03-09    0.032978
2016-03-10    0.032116
2016-03-11    0.033107
2016-03-12    0.036965
2016-03-13    0.017028
2016-03-14    0.035004
2016-03-15    0.033926
2016-03-16    0.030025
2016-03-17    0.031016
2016-03-18    0.013450
2016-03-19    0.033387
2016-03-20    0.038258
2016-03-21    0.037849
2016-03-22    0.032762
2016-03-23    0.032180
2016-03-24    0.029033
2016-03-25    0.031404
2016-03-26    0.032439
2016-03-27    0.031038
2016-03-28    0.034982
2016-03-29    0.033754
2016-03-30    0.033452
2016-03-31    0.031965
2016-04-01    0.033818
2016-04-02    0.035370
2016-04-03    0.038862
2016-04-04    0.036987
2016-04-05    0.011833
2016-04-06    0.003233
2016-04-07    0.001229
Name: ad_created, Length: 76, dtype: float64

According to the above list, data was created in a span of time since 2015 to 2016.

In [27]:
autos['last_seen'].str[:10].value_counts(normalize = True, dropna = False).sort_index()

2016-03-05    0.001078
2016-03-06    0.004246
2016-03-07    0.005345
2016-03-08    0.007134
2016-03-09    0.009527
2016-03-10    0.010475
2016-03-11    0.012243
2016-03-12    0.023731
2016-03-13    0.008794
2016-03-14    0.012437
2016-03-15    0.015627
2016-03-16    0.016230
2016-03-17    0.027826
2016-03-18    0.007264
2016-03-19    0.015497
2016-03-20    0.020713
2016-03-21    0.020498
2016-03-22    0.021339
2016-03-23    0.018558
2016-03-24    0.019506
2016-03-25    0.018860
2016-03-26    0.016640
2016-03-27    0.015584
2016-03-28    0.020800
2016-03-29    0.021813
2016-03-30    0.024335
2016-03-31    0.023774
2016-04-01    0.022912
2016-04-02    0.024766
2016-04-03    0.025003
2016-04-04    0.024421
2016-04-05    0.126027
2016-04-06    0.223817
2016-04-07    0.133182
Name: last_seen, dtype: float64

Data last viewed seems to indicate that ads were taken down sistematically. It's possible the car was sold or the listing expired. The last 3 days seems strange, there's not enough data to interpret what happened.

In [28]:
autos["registration_year"].describe()

count    46395.000000
mean      2004.886259
std         88.508813
min       1000.000000
25%       1999.000000
50%       2004.000000
75%       2008.000000
max       9999.000000
Name: registration_year, dtype: float64

According to this, it seems there was wrong data input. Let's filter these to 1985 to 2016 and see how much data need to be dropped.

In [29]:
(~autos["registration_year"].between(1970,2016)).sum() / autos.shape[0]

0.04366849876064231

If we drop this percentage our erased data will be just over 10%, which for me is a good indicator.

In [30]:
autos = autos[autos["registration_year"].between(1970,2016)]
autos["registration_year"].describe()

count    44369.000000
mean      2003.296806
std          6.496227
min       1970.000000
25%       1999.000000
50%       2003.000000
75%       2008.000000
max       2016.000000
Name: registration_year, dtype: float64

## 6.- Data Analysis for Car Brands.

Use aggregation to explore date from Car Brands and Price.

In [31]:
autos["brand"].value_counts(normalize = True)

volkswagen        0.212085
bmw               0.113458
opel              0.103451
mercedes_benz     0.099867
audi              0.089612
ford              0.066172
renault           0.045460
peugeot           0.029660
fiat              0.024386
seat              0.018233
skoda             0.016859
mazda             0.015236
nissan            0.015101
smart             0.014808
citroen           0.014086
toyota            0.013252
hyundai           0.010210
volvo             0.009173
mini              0.009151
sonstige_autos    0.008474
mitsubishi        0.008001
honda             0.007956
kia               0.007325
alfa_romeo        0.006761
porsche           0.005928
suzuki            0.005860
chevrolet         0.005747
chrysler          0.003584
dacia             0.002772
jeep              0.002389
daihatsu          0.002299
land_rover        0.002164
subaru            0.002096
saab              0.001645
jaguar            0.001533
daewoo            0.001330
rover             0.001307
lancia            0.001014
trabant           0.000969
lada              0.000586
Name: brand, dtype: float64

Let's drop from our analysis all cars with less than 2% of representation.

In [32]:
brands = autos["brand"].value_counts(normalize = True)
represented_brands = brands[brands > .02].index
print(represented_brands)

Index(['volkswagen', 'bmw', 'opel', 'mercedes_benz', 'audi', 'ford', 'renault',
       'peugeot', 'fiat'],
      dtype='object')

Now let's analyze price means for these cars.

In [33]:
price_mean_by_brand = {}

for b in represented_brands:
    selected_rows = autos[autos["brand"] == b]
    mean = selected_rows["price"].mean()
    price_mean_by_brand[b] = int(mean)

price_mean_by_brand

{'audi': 9435,
 'bmw': 8354,
 'fiat': 3039,
 'ford': 3804,
 'mercedes_benz': 8519,
 'opel': 3221,
 'peugeot': 3254,
 'renault': 2673,
 'volkswagen': 5632}

German cars tend to sell for more, as Audi, BMW, Mercedes Benz and Volkswagen are in the top positions.

In [34]:
pmbb_series = pd.Series(price_mean_by_brand)
pmbb_series

audi             9435
bmw              8354
fiat             3039
ford             3804
mercedes_benz    8519
opel             3221
peugeot          3254
renault          2673
volkswagen       5632
dtype: int64

In [35]:
mileage_mean_by_brand = {}

for b in represented_brands:
    selected_rows = autos[autos["brand"] == b]
    mean = selected_rows["odometer_km"].mean()
    mileage_mean_by_brand[b] = int(mean)

mileage_mean_by_brand

{'audi': 129149,
 'bmw': 133049,
 'fiat': 116326,
 'ford': 124409,
 'mercedes_benz': 131380,
 'opel': 128955,
 'peugeot': 126618,
 'renault': 127471,
 'volkswagen': 128516}

In [36]:
mmbb_series = pd.Series(mileage_mean_by_brand)
mmbb_series

audi             129149
bmw              133049
fiat             116326
ford             124409
mercedes_benz    131380
opel             128955
peugeot          126618
renault          127471
volkswagen       128516
dtype: int64

In [37]:
mean_database = pd.DataFrame(mmbb_series, columns=['mean_mileage'])
mean_database

               mean_mileage
audi                 129149
bmw                  133049
fiat                 116326
ford                 124409
mercedes_benz        131380
opel                 128955
peugeot              126618
renault              127471
volkswagen           128516

In [38]:
mean_database["mean_price"] = pmbb_series
mean_database

               mean_mileage  mean_price
audi                 129149        9435
bmw                  133049        8354
fiat                 116326        3039
ford                 124409        3804
mercedes_benz        131380        8519
opel                 128955        3221
peugeot              126618        3254
renault              127471        2673
volkswagen           128516        5632

With pandas series constructor and pandas dataframe constructor, I was able to convert a dictionary into a Series object, and then convert the Series object into a Dataframe object. Since pandas knows how to arrange by index, the data gets accurately positioned.

## 7.- Data Cleaning.
Now I will change the deutsch words for english, convert dates from strings to integers and extract, if any, information from the name column.

In [39]:
autos["vehicle_type"].unique()

array(['bus', 'limousine', 'kleinwagen', 'kombi', nan, 'coupe', 'suv',
       'cabrio', 'andere'], dtype=object)

There's some data marked as nan. I will change that to not_specified and see if from name column can extract vehicle type.

In [40]:
vehicle_type_dict = {"bus": "bus",
                     "limousine": "limousine",
                     "kleinwagen": "small_car", 
                     "kombi": "station wagon",
                     "copue": "coupe",
                     "suv": "suv", 
                     "cabrio": "convertible",
                     "andere": "other"}
autos["vehicle_type"].replace(vehicle_type_dict,inplace=True)
autos["vehicle_type"].fillna("not_specified", inplace=True)

In [41]:
autos["gear_box"].unique()

array(['manuell', 'automatik', nan], dtype=object)

In [42]:
gear_box_dict = {"manuell": "manual", "automatik": "automatic"}
autos["gear_box"].replace(gear_box_dict,inplace=True)
autos["gear_box"].fillna("not_specified", inplace=True)

In [43]:
autos["fuel_type"].unique()

array(['lpg', 'benzin', 'diesel', nan, 'cng', 'hybrid', 'elektro',
       'andere'], dtype=object)

In [44]:
fuel_type_dict = {"lpg": "lp_gas", "benzin": "gasoline", "cng": "natural_gas",
                  "hybrid": "hybrid", "elektro": "electric", "andere": "other"}
autos["fuel_type"].replace(fuel_type_dict,inplace=True)
autos["fuel_type"].fillna("not_specified", inplace=True)

In [45]:
autos["unrepaired_damage"].unique()

array(['nein', nan, 'ja'], dtype=object)

In [46]:
unrepaired_damage_dict = {"nein": "no", "ja": "yes"}
autos["unrepaired_damage"].replace(unrepaired_damage_dict,inplace=True)
autos["unrepaired_damage"].fillna("not_specified", inplace=True)

In [47]:
autos

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gear_box,power_PS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,5000,control,bus,2004,manual,158,andere,150000,3,lp_gas,peugeot,no,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,8500,control,limousine,1997,automatic,286,7er,150000,6,gasoline,bmw,no,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,8990,test,limousine,2009,manual,102,golf,70000,7,gasoline,volkswagen,no,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,4350,control,small_car,2007,automatic,71,fortwo,70000,6,gasoline,smart,no,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,1350,test,station wagon,2003,manual,0,focus,150000,7,gasoline,ford,no,2016-04-01 00:00:00,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,7900,test,bus,2006,automatic,150,voyager,150000,4,diesel,chrysler,not_specified,2016-03-21 00:00:00,22962,2016-04-06 09:45:21
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,1990,control,limousine,1998,manual,90,golf,150000,12,diesel,volkswagen,no,2016-03-16 00:00:00,53474,2016-04-07 03:17:32
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,590,control,bus,1997,manual,90,megane,150000,7,gasoline,renault,no,2016-03-16 00:00:00,15749,2016-04-06 10:46:35
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,350,control,not_specified,2000,not_specified,0,NaN,150000,0,gasoline,mercedes_benz,not_specified,2016-03-16 00:00:00,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,5299,control,small_car,2010,automatic,71,fortwo,50000,9,gasoline,smart,no,2016-03-31 00:00:00,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,1350,control,limousine,1999,manual,101,a3,150000,11,gasoline,audi,no,2016-03-23 00:00:00,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,3999,test,small_car,2007,manual,75,clio,150000,9,gasoline,renault,not_specified,2016-03-23 00:00:00,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,18900,test,coupe,1982,automatic,203,NaN,80000,6,gasoline,sonstige_autos,no,2016-04-01 00:00:00,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,350,test,station wagon,1999,manual,101,vectra,150000,5,gasoline,opel,no,2016-03-16 00:00:00,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,5500,test,coupe,1990,manual,205,scirocco,150000,6,gasoline,volkswagen,no,2016-03-29 00:00:00,74821,2016-04-05 20:46:26
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,4150,control,suv,2004,manual,124,andere,150000,2,lp_gas,mazda,no,2016-03-17 00:00:00,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,3500,test,station wagon,2003,manual,131,a4,150000,5,diesel,audi,not_specified,2016-03-05 00:00:00,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,41500,test,convertible,2004,manual,320,911,150000,4,gasoline,porsche,no,2016-03-06 00:00:00,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,25450,control,convertible,2015,manual,184,cooper,10000,1,gasoline,mini,no,2016-03-28 00:00:00,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,7999,control,bus,2010,manual,120,NaN,150000,2,diesel,peugeot,no,2016-03-10 00:00:00,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,48500,control,limousine,2014,automatic,306,5er,30000,12,gasoline,bmw,no,2016-04-03 00:00:00,22547,2016-04-07 13:16:50
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,777,control,small_car,1992,manual,54,polo,125000,2,gasoline,volkswagen,no,2016-04-03 00:00:00,38110,2016-04-05 23:46:48
28,2016-03-19 21:56:19,MINI_Cooper_D,5250,control,small_car,2007,manual,110,cooper,150000,7,diesel,mini,yes,2016-03-19 00:00:00,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,4999,test,station wagon,2004,automatic,204,e_klasse,150000,10,diesel,mercedes_benz,no,2016-04-02 00:00:00,47638,2016-04-02 12:45:44
31,2016-03-14 16:53:09,Noch_gut_erhaltenen_C_320,2850,test,station wagon,2002,automatic,218,c_klasse,150000,7,gasoline,mercedes_benz,no,2016-03-14 00:00:00,41065,2016-03-16 07:19:04
32,2016-03-20 05:03:03,Corsa_mit_TÃœV_5.2016,350,control,small_car,1999,manual,0,corsa,150000,7,gasoline,opel,not_specified,2016-03-20 00:00:00,27619,2016-04-06 03:15:20
33,2016-03-15 12:25:26,Audi_A3_2.0_TDI_Sportback_DPF_Kupplung_defekt_...,4800,test,station wagon,2006,manual,140,a3,150000,8,diesel,audi,no,2016-03-15 00:00:00,61169,2016-04-07 13:15:31
34,2016-04-05 07:55:07,Bmw_530d__navi_tuv03/18,2600,test,station wagon,2000,automatic,193,5er,150000,6,diesel,bmw,not_specified,2016-04-05 00:00:00,95111,2016-04-07 12:15:47
35,2016-03-29 21:52:56,Ford_Mondeo,1200,test,station wagon,1998,manual,0,mondeo,150000,12,gasoline,ford,no,2016-03-29 00:00:00,52428,2016-04-06 08:45:35
36,2016-03-16 23:46:31,Ford_Mondeo_2.0_Turnier_TDCi_DPF_Titanium,7500,test,station wagon,2007,manual,131,mondeo,150000,11,diesel,ford,no,2016-03-16 00:00:00,34246,2016-04-05 16:21:16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49967,2016-03-12 11:50:17,VW_Passat_2_0_TDI_comfortline,4999,test,station wagon,2006,manual,140,passat,150000,5,diesel,volkswagen,not_specified,2016-03-12 00:00:00,70619,2016-03-17 09:45:12
49968,2016-04-01 17:49:15,Mercedes_Benz_190_D_2.5_Automatik,2100,test,limousine,1986,automatic,90,andere,150000,9,diesel,mercedes_benz,no,2016-04-01 00:00:00,40227,2016-04-05 13:16:35
49969,2016-03-17 18:49:02,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,4500,control,suv,2005,manual,136,x_trail,150000,5,diesel,nissan,no,2016-03-17 00:00:00,17379,2016-03-25 23:18:15
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,15800,control,bus,2010,automatic,136,c4,60000,4,diesel,citroen,no,2016-03-21 00:00:00,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,950,test,small_car,2001,manual,50,lupo,150000,4,gasoline,volkswagen,no,2016-03-29 00:00:00,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,3300,control,bus,2004,automatic,150,vito,150000,10,diesel,mercedes_benz,yes,2016-03-26 00:00:00,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,6000,control,convertible,2004,manual,163,slk,150000,11,gasoline,mercedes_benz,no,2016-03-27 00:00:00,53567,2016-03-27 08:25:24
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,9700,control,small_car,2012,automatic,88,jazz,100000,11,hybrid,honda,no,2016-03-27 00:00:00,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,5900,test,station wagon,1992,automatic,150,80,150000,12,gasoline,audi,no,2016-03-19 00:00:00,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,5500,control,limousine,2003,manual,116,c_klasse,150000,2,diesel,mercedes_benz,no,2016-03-31 00:00:00,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,900,control,limousine,1996,automatic,136,e_klasse,150000,9,gasoline,mercedes_benz,yes,2016-04-04 00:00:00,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,11000,test,small_car,2011,manual,90,polo,70000,11,diesel,volkswagen,no,2016-03-20 00:00:00,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,400,control,station wagon,1995,manual,105,escort,125000,3,gasoline,ford,not_specified,2016-03-12 00:00:00,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,2000,control,station wagon,1998,manual,115,astra,150000,12,gasoline,opel,no,2016-03-15 00:00:00,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,1950,control,small_car,2004,manual,0,fabia,90000,7,gasoline,skoda,not_specified,2016-03-29 00:00:00,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,600,test,small_car,1999,manual,101,focus,150000,4,gasoline,ford,not_specified,2016-03-06 00:00:00,52477,2016-03-09 06:16:08
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,1000,control,not_specified,1995,automatic,0,NaN,150000,0,gasoline,volkswagen,not_specified,2016-04-02 00:00:00,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,15900,control,limousine,2010,automatic,218,300c,125000,11,diesel,chrysler,no,2016-04-04 00:00:00,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,21990,control,limousine,2013,manual,150,a3,50000,11,diesel,audi,no,2016-03-22 00:00:00,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,9550,control,coupe,2001,manual,231,3er,150000,10,gasoline,bmw,no,2016-03-28 00:00:00,83646,2016-04-07 02:17:40
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,17500,test,limousine,2012,manual,156,a_klasse,30000,12,gasoline,mercedes_benz,no,2016-03-21 00:00:00,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,500,control,not_specified,2016,manual,0,twingo,150000,0,gasoline,renault,not_specified,2016-03-06 00:00:00,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,4800,control,small_car,2009,manual,120,andere,125000,9,lp_gas,fiat,no,2016-03-10 00:00:00,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,1650,control,small_car,1997,manual,0,NaN,150000,7,gasoline,audi,not_specified,2016-03-15 00:00:00,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,5000,control,station wagon,2001,automatic,299,a6,150000,1,gasoline,audi,no,2016-03-22 00:00:00,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,24900,control,limousine,2011,automatic,239,q5,100000,1,diesel,audi,no,2016-03-27 00:00:00,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,1980,control,convertible,1996,manual,75,astra,150000,5,gasoline,opel,no,2016-03-28 00:00:00,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,13200,test,convertible,2014,automatic,69,500,5000,11,gasoline,fiat,no,2016-04-02 00:00:00,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,22900,control,station wagon,2013,manual,150,a3,40000,11,diesel,audi,no,2016-03-08 00:00:00,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,1250,control,limousine,1996,manual,101,vectra,150000,1,gasoline,opel,no,2016-03-13 00:00:00,45897,2016-04-06 21:18:48

All data in these columns marked as `nan` was changed to `not_specified`. I will try to extract this data from the name column. But first I will change date format from string to integer.

In [48]:
autos['date_crawled'] = autos['date_crawled'].str[:10].str.replace("-","").astype(int)
autos['ad_created'] = autos['ad_created'].str[:10].str.replace("-","").astype(int)
autos['last_seen'] = autos['last_seen'].str[:10].str.replace("-","").astype(int)

In [49]:
autos

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gear_box,power_PS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,20160326,Peugeot_807_160_NAVTECH_ON_BOARD,5000,control,bus,2004,manual,158,andere,150000,3,lp_gas,peugeot,no,20160326,79588,20160406
1,20160404,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,8500,control,limousine,1997,automatic,286,7er,150000,6,gasoline,bmw,no,20160404,71034,20160406
2,20160326,Volkswagen_Golf_1.6_United,8990,test,limousine,2009,manual,102,golf,70000,7,gasoline,volkswagen,no,20160326,35394,20160406
3,20160312,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,4350,control,small_car,2007,automatic,71,fortwo,70000,6,gasoline,smart,no,20160312,33729,20160315
4,20160401,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,1350,test,station wagon,2003,manual,0,focus,150000,7,gasoline,ford,no,20160401,39218,20160401
5,20160321,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,7900,test,bus,2006,automatic,150,voyager,150000,4,diesel,chrysler,not_specified,20160321,22962,20160406
7,20160316,Golf_IV_1.9_TDI_90PS,1990,control,limousine,1998,manual,90,golf,150000,12,diesel,volkswagen,no,20160316,53474,20160407
9,20160316,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,590,control,bus,1997,manual,90,megane,150000,7,gasoline,renault,no,20160316,15749,20160406
11,20160316,Mercedes_A140_Motorschaden,350,control,not_specified,2000,not_specified,0,NaN,150000,0,gasoline,mercedes_benz,not_specified,20160316,17498,20160316
12,20160331,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,5299,control,small_car,2010,automatic,71,fortwo,50000,9,gasoline,smart,no,20160331,34590,20160406
13,20160323,Audi_A3_1.6_tuning,1350,control,limousine,1999,manual,101,a3,150000,11,gasoline,audi,no,20160323,12043,20160401
14,20160323,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,3999,test,small_car,2007,manual,75,clio,150000,9,gasoline,renault,not_specified,20160323,81737,20160401
15,20160401,Corvette_C3_Coupe_T_Top_Crossfire_Injection,18900,test,coupe,1982,automatic,203,NaN,80000,6,gasoline,sonstige_autos,no,20160401,61276,20160402
16,20160316,Opel_Vectra_B_Kombi,350,test,station wagon,1999,manual,101,vectra,150000,5,gasoline,opel,no,20160316,57299,20160318
17,20160329,Volkswagen_Scirocco_2_G60,5500,test,coupe,1990,manual,205,scirocco,150000,6,gasoline,volkswagen,no,20160329,74821,20160405
19,20160317,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,4150,control,suv,2004,manual,124,andere,150000,2,lp_gas,mazda,no,20160317,40878,20160317
20,20160305,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,3500,test,station wagon,2003,manual,131,a4,150000,5,diesel,audi,not_specified,20160305,53913,20160307
21,20160306,Porsche_911_Carrera_4S_Cabrio,41500,test,convertible,2004,manual,320,911,150000,4,gasoline,porsche,no,20160306,65428,20160405
22,20160328,MINI_Cooper_S_Cabrio,25450,control,convertible,2015,manual,184,cooper,10000,1,gasoline,mini,no,20160328,44789,20160401
23,20160310,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,7999,control,bus,2010,manual,120,NaN,150000,2,diesel,peugeot,no,20160310,30900,20160317
24,20160403,BMW_535i_xDrive_Sport_Aut.,48500,control,limousine,2014,automatic,306,5er,30000,12,gasoline,bmw,no,20160403,22547,20160407
26,20160403,Volkswagen_Polo_Fox,777,control,small_car,1992,manual,54,polo,125000,2,gasoline,volkswagen,no,20160403,38110,20160405
28,20160319,MINI_Cooper_D,5250,control,small_car,2007,manual,110,cooper,150000,7,diesel,mini,yes,20160319,15745,20160407
29,20160402,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,4999,test,station wagon,2004,automatic,204,e_klasse,150000,10,diesel,mercedes_benz,no,20160402,47638,20160402
31,20160314,Noch_gut_erhaltenen_C_320,2850,test,station wagon,2002,automatic,218,c_klasse,150000,7,gasoline,mercedes_benz,no,20160314,41065,20160316
32,20160320,Corsa_mit_TÃœV_5.2016,350,control,small_car,1999,manual,0,corsa,150000,7,gasoline,opel,not_specified,20160320,27619,20160406
33,20160315,Audi_A3_2.0_TDI_Sportback_DPF_Kupplung_defekt_...,4800,test,station wagon,2006,manual,140,a3,150000,8,diesel,audi,no,20160315,61169,20160407
34,20160405,Bmw_530d__navi_tuv03/18,2600,test,station wagon,2000,automatic,193,5er,150000,6,diesel,bmw,not_specified,20160405,95111,20160407
35,20160329,Ford_Mondeo,1200,test,station wagon,1998,manual,0,mondeo,150000,12,gasoline,ford,no,20160329,52428,20160406
36,20160316,Ford_Mondeo_2.0_Turnier_TDCi_DPF_Titanium,7500,test,station wagon,2007,manual,131,mondeo,150000,11,diesel,ford,no,20160316,34246,20160405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49967,20160312,VW_Passat_2_0_TDI_comfortline,4999,test,station wagon,2006,manual,140,passat,150000,5,diesel,volkswagen,not_specified,20160312,70619,20160317
49968,20160401,Mercedes_Benz_190_D_2.5_Automatik,2100,test,limousine,1986,automatic,90,andere,150000,9,diesel,mercedes_benz,no,20160401,40227,20160405
49969,20160317,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,4500,control,suv,2005,manual,136,x_trail,150000,5,diesel,nissan,no,20160317,17379,20160325
49970,20160321,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,15800,control,bus,2010,automatic,136,c4,60000,4,diesel,citroen,no,20160321,14947,20160407
49971,20160329,W.Lupo_1.0,950,test,small_car,2001,manual,50,lupo,150000,4,gasoline,volkswagen,no,20160329,65197,20160329
49972,20160326,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,3300,control,bus,2004,automatic,150,vito,150000,10,diesel,mercedes_benz,yes,20160326,65326,20160328
49973,20160327,Mercedes_Benz_SLK_200_Kompressor,6000,control,convertible,2004,manual,163,slk,150000,11,gasoline,mercedes_benz,no,20160327,53567,20160327
49975,20160327,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,9700,control,small_car,2012,automatic,88,jazz,100000,11,hybrid,honda,no,20160327,84385,20160405
49976,20160319,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,5900,test,station wagon,1992,automatic,150,80,150000,12,gasoline,audi,no,20160319,36100,20160407
49977,20160331,Mercedes_Benz_C200_Cdi_W203,5500,control,limousine,2003,manual,116,c_klasse,150000,2,diesel,mercedes_benz,no,20160331,33739,20160406
49978,20160404,Mercedes_Benz_E_200_Classic,900,control,limousine,1996,automatic,136,e_klasse,150000,9,gasoline,mercedes_benz,yes,20160404,24405,20160406
49979,20160320,Volkswagen_Polo_1.6_TDI_Style,11000,test,small_car,2011,manual,90,polo,70000,11,diesel,volkswagen,no,20160320,48455,20160407
49980,20160312,Ford_Escort_Turnier_16V,400,control,station wagon,1995,manual,105,escort,125000,3,gasoline,ford,not_specified,20160312,56218,20160406
49981,20160315,Opel_Astra_Kombi_mit_Anhaengerkupplung,2000,control,station wagon,1998,manual,115,astra,150000,12,gasoline,opel,no,20160315,86859,20160405
49982,20160329,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,1950,control,small_car,2004,manual,0,fabia,90000,7,gasoline,skoda,not_specified,20160329,45884,20160329
49983,20160306,Ford_focus_99,600,test,small_car,1999,manual,101,focus,150000,4,gasoline,ford,not_specified,20160306,52477,20160309
49985,20160402,Verkaufe_meinen_vw_vento!,1000,control,not_specified,1995,automatic,0,NaN,150000,0,gasoline,volkswagen,not_specified,20160402,30900,20160406
49986,20160404,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,15900,control,limousine,2010,automatic,218,300c,125000,11,diesel,chrysler,no,20160404,73527,20160406
49987,20160322,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,21990,control,limousine,2013,manual,150,a3,50000,11,diesel,audi,no,20160322,94362,20160326
49988,20160328,BMW_330_Ci,9550,control,coupe,2001,manual,231,3er,150000,10,gasoline,bmw,no,20160328,83646,20160407
49990,20160321,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,17500,test,limousine,2012,manual,156,a_klasse,30000,12,gasoline,mercedes_benz,no,20160321,58239,20160406
49991,20160306,Kleinwagen,500,control,not_specified,2016,manual,0,twingo,150000,0,gasoline,renault,not_specified,20160306,61350,20160306
49992,20160310,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,4800,control,small_car,2009,manual,120,andere,125000,9,lp_gas,fiat,no,20160310,68642,20160313
49993,20160315,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,1650,control,small_car,1997,manual,0,NaN,150000,7,gasoline,audi,not_specified,20160315,65203,20160406
49994,20160322,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,5000,control,station wagon,2001,automatic,299,a6,150000,1,gasoline,audi,no,20160322,46537,20160406
49995,20160327,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,24900,control,limousine,2011,automatic,239,q5,100000,1,diesel,audi,no,20160327,82131,20160401
49996,20160328,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,1980,control,convertible,1996,manual,75,astra,150000,5,gasoline,opel,no,20160328,44807,20160402
49997,20160402,Fiat_500_C_1.2_Dualogic_Lounge,13200,test,convertible,2014,automatic,69,500,5000,11,gasoline,fiat,no,20160402,73430,20160404
49998,20160308,Audi_A3_2.0_TDI_Sportback_Ambition,22900,control,station wagon,2013,manual,150,a3,40000,11,diesel,audi,no,20160308,35683,20160405
49999,20160314,Opel_Vectra_1.6_16V,1250,control,limousine,1996,manual,101,vectra,150000,1,gasoline,opel,no,20160313,45897,20160406

Now to check on the name column.

In [50]:
name_dataframe = pd.DataFrame(autos["name"].str.split("_", expand = True))
name_dataframe

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,Peugeot,807,160,NAVTECH,ON,BOARD,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,BMW,740i,4,4,Liter,HAMANN,UMBAU,Mega,Optik,None,...,None,None,None,None,None,None,None,None,None,None
2,Volkswagen,Golf,1.6,United,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,Smart,smart,fortwo,coupe,softouch/F1/Klima/Panorama,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,Ford,Focus,1,6,Benzin,TÃœV,neu,ist,sehr,gepflegt.mit,...,None,None,None,None,None,None,None,None,None,None
5,Chrysler,Grand,Voyager,2.8,CRD,Aut.Limited,StowÂ´n,Go,Sitze,7Sitze,...,None,None,None,None,None,None,None,None,None,None
7,Golf,IV,1.9,TDI,90PS,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9,Renault,Megane,Scenic,1.6e,RT,Klimaanlage,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
11,Mercedes,A140,Motorschaden,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
12,Smart,smart,fortwo,coupe,softouch,pure,MHD,Panoramadach,,Klima,...,None,None,None,None,None,None,None,None,None,None
13,Audi,A3,1.6,tuning,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
14,Renault,Clio,3,,Dynamique,1.2,,16,V;,viele,...,None,None,None,None,None,None,None,None,None,None
15,Corvette,C3,Coupe,T,Top,Crossfire,Injection,None,None,None,...,None,None,None,None,None,None,None,None,None,None
16,Opel,Vectra,B,Kombi,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
17,Volkswagen,Scirocco,2,G60,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
19,mazda,tribute,2.0,mit,gas,und,tuev,neu,2018,None,...,None,None,None,None,None,None,None,None,None,None
20,Audi,A4,Avant,1.9,TDI,*6,Gang*AHK*Klimatronik*DPF*AGR*TÃœV*,None,None,None,...,None,None,None,None,None,None,None,None,None,None
21,Porsche,911,Carrera,4S,Cabrio,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
22,MINI,Cooper,S,Cabrio,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
23,Peugeot,Boxer,2,2,HDi,120,Ps,9,Sitzer,inkl,...,None,None,None,None,None,None,None,None,None,None
24,BMW,535i,xDrive,Sport,Aut.,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
26,Volkswagen,Polo,Fox,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
28,MINI,Cooper,D,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
29,Mercedes,Benz,E,320,T,CDI,Avantgarde,DPF7,Sitze,,...,None,None,None,None,None,None,None,None,None,None
31,Noch,gut,erhaltenen,C,320,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
32,Corsa,mit,TÃœV,5.2016,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
33,Audi,A3,2.0,TDI,Sportback,DPF,Kupplung,defekt,fahrber,None,...,None,None,None,None,None,None,None,None,None,None
34,Bmw,530d,,navi,tuv03/18,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
35,Ford,Mondeo,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
36,Ford,Mondeo,2.0,Turnier,TDCi,DPF,Titanium,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49967,VW,Passat,2,0,TDI,comfortline,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49968,Mercedes,Benz,190,D,2.5,Automatik,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49969,Nissan,X,Trail,2.2,dCi,4x4,Sport,m.AHZ,None,None,...,None,None,None,None,None,None,None,None,None,None
49970,c4,Grand,Picasso,mit,Automatik,Leder,Navi,Tempomat,,7,...,None,None,None,None,None,None,None,None,None,None
49971,W.Lupo,1.0,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49972,Mercedes,Benz,Vito,115,CDI,Extralang,Aut.,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49973,Mercedes,Benz,SLK,200,Kompressor,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49975,Honda,Jazz,1.3,DSi,i,VTEC,IMA,CVT,Comfort,None,...,None,None,None,None,None,None,None,None,None,None
49976,Audi,80,Avant,2.6,E,,Vollausstattung!!,Einzigartig!!!,None,None,...,None,None,None,None,None,None,None,None,None,None
49977,Mercedes,Benz,C200,Cdi,W203,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49978,Mercedes,Benz,E,200,Classic,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49979,Volkswagen,Polo,1.6,TDI,Style,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49980,Ford,Escort,Turnier,16V,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49981,Opel,Astra,Kombi,mit,Anhaengerkupplung,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49982,Skoda,Fabia,4,Tuerer,Bj:2004,,85.000Tkm,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49983,Ford,focus,99,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49985,Verkaufe,meinen,vw,vento!,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49986,Chrysler,300C,3.0,CRD,DPF,Automatik,Voll,Ausstattung,None,None,...,None,None,None,None,None,None,None,None,None,None
49987,Audi,A3,Limousine,2.0,TDI,DPF,Ambition,,NAVI,,...,None,None,None,None,None,None,None,None,None,None
49988,BMW,330,Ci,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49990,Mercedes,Benz,A,200,,BlueEFFICIENCY,,Urban,None,None,...,None,None,None,None,None,None,None,None,None,None
49991,Kleinwagen,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49992,Fiat,Grande,Punto,1.4,T,Jet,16V,Sport,None,None,...,None,None,None,None,None,None,None,None,None,None
49993,Audi,A3,,1,8l,,Silber;,schoenes,Fahrzeug,None,...,None,None,None,None,None,None,None,None,None,None
49994,Audi,A6,,S6,,Avant,4.2,quattro,eventuell,Tausch,...,None,None,None,None,None,None,None,None,None,None
49995,Audi,Q5,3.0,TDI,qu.,S,tr.,,Navi,,...,None,None,None,None,None,None,None,None,None,None
49996,Opel,Astra,F,Cabrio,Bertone,Edition,,,TÃœV,neu+Reifen,...,None,None,None,None,None,None,None,None,None,None
49997,Fiat,500,C,1.2,Dualogic,Lounge,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49998,Audi,A3,2.0,TDI,Sportback,Ambition,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
49999,Opel,Vectra,1.6,16V,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

I may be able to extract data on the engine from this, but I decided against it to avoid scope creep.

## 8.- Data Analysis.
Now I will find the most common brand/model combinations, split odometer_km into groups and analyze average prices per group and lastly determine how much cheaper cars with damage are than their non-damaged peers.

In [51]:
autos["model_brand"] = autos["model"] + " " + autos["brand"]
autos["model_brand"].head()

0     andere peugeot
1            7er bmw
2    golf volkswagen
3       fortwo smart
4         focus ford
Name: model_brand, dtype: object

In [52]:
autos["model_brand"].value_counts(normalize = True).head(20)

golf volkswagen           0.083455
3er bmw                   0.060249
polo volkswagen           0.033584
corsa opel                0.032502
passat volkswagen         0.031349
astra opel                0.030078
a4 audi                   0.028571
c_klasse mercedes_benz    0.026665
5er bmw                   0.026430
e_klasse mercedes_benz    0.022358
a3 audi                   0.019369
a6 audi                   0.018640
focus ford                0.017298
transporter volkswagen    0.015768
fiesta ford               0.015180
2_reihe peugeot           0.013862
fortwo smart              0.012874
twingo renault            0.012591
a_klasse mercedes_benz    0.012568
1er bmw                   0.012120
Name: model_brand, dtype: float64

In [53]:
models = autos["model_brand"].value_counts(normalize = True)
represented_models = models[models > .02].index
print(represented_models)

Index(['golf volkswagen', '3er bmw', 'polo volkswagen', 'corsa opel',
       'passat volkswagen', 'astra opel', 'a4 audi', 'c_klasse mercedes_benz',
       '5er bmw', 'e_klasse mercedes_benz'],
      dtype='object')

In [54]:
models_series = pd.Series(represented_models)
models_series

0           golf volkswagen
1                   3er bmw
2           polo volkswagen
3                corsa opel
4         passat volkswagen
5                astra opel
6                   a4 audi
7    c_klasse mercedes_benz
8                   5er bmw
9    e_klasse mercedes_benz
dtype: object

In [55]:
brand_model_database = pd.DataFrame(models_series)
brand_model_database_real = pd.DataFrame(brand_model_database[0].str.split(" ", expand = True))
brand_model_database_real.rename(columns={0: "model" , 1: "brand"}, inplace = True)
brand_model_database_real

      model          brand
0      golf     volkswagen
1       3er            bmw
2      polo     volkswagen
3     corsa           opel
4    passat     volkswagen
5     astra           opel
6        a4           audi
7  c_klasse  mercedes_benz
8       5er            bmw
9  e_klasse  mercedes_benz

I had to concatenate the values in columns model and brand to value count which model was the most common, create a series object and dataframe object and later split that dataframe object to view both columns in a single list.
Is there a way to do this less code?

The most common brand/model combinations German automaker cars, mainly Volkswagen.

Now to split odometer_km into groups.

In [56]:
autos["odometer_km"].value_counts()

150000    28446
125000     4719
100000     1979
90000      1627
80000      1347
70000      1157
60000      1095
50000       969
40000       784
30000       742
20000       704
5000        579
10000       221
Name: odometer_km, dtype: int64

In [57]:
odometer_km = (150000,125000,100000,90000,80000,70000,60000,50000,
               40000, 30000, 20000, 10000, 5000)

In [58]:
def mean_analysis(odometer):
    
    for km in odometer:
    
        km_odometer = autos[autos["odometer_km"] == km]
        brands = km_odometer["brand"].value_counts(normalize = True)
        represented_brands = brands[brands > .015].index
    
        price_mean_by_brand = {}
    
        for b in represented_brands:
            selected_rows = km_odometer[km_odometer["brand"] == b]
            mean = selected_rows["price"].mean()
            price_mean_by_brand[b] = int(mean)
        
        new_series = pd.Series(price_mean_by_brand)
        if km == 150000:
            new_database = pd.DataFrame(new_series, columns=[km])
        elif km != 5000:
            new_database[km] = new_series
        else:
            new_database[km] = new_series
                        
    return new_database

In [59]:
brands_by_odometer_by_price = mean_analysis(odometer_km)
brands_by_odometer_by_price

,150000,125000,100000,90000,80000,70000,60000,50000,40000,30000,20000,10000,5000
audi,5744,12438,15276,16142,16471,21327,20630,22786,26383,26527,27085,28339.0,14146
bmw,5790,11454,13353,14486,16323,17784,19408,23936,24586,24280,25155,32568.0,8486
fiat,1758,2481,3299,3588,4542,4657,5125,4814,6870,7636,7993,11306.0,6571
ford,2360,4048,4062,4176,6143,6838,6465,7255,10776,13076,13255,14971.0,7355
mercedes_benz,5710,10000,14121,15430,16041,17505,20974,22709,25136,19138,25816,31929.0,13209
opel,2064,3555,4593,4093,6115,7685,6917,8872,9092,10923,9969,13611.0,5166
peugeot,2005,3610,4964,4100,5263,6878,6473,7791,10325,11612,5007,NaN,4027
renault,1671,2496,3281,3833,4128,5774,6960,7145,6701,12561,9519,9233.0,5436
seat,2508,4211,5066,6273,7248,8173,9931,10066,12133,14811,11945,NaN,9620
volkswagen,3664,6137,7961,8769,10808,11582,12765,13414,15678,15492,17943,20519.0,5321

According to the analysis above, it seems cars begin to lose value faster after they reach 30,000 to 50,000 km. Let's see how much value they lose if they have unrepaired damage.

In [60]:
unrepaired_damage = ("yes", "no", "not_specified")

In [61]:
def mean_analysis(odometer):
    
    for km in odometer:
    
        km_odometer = autos[autos["unrepaired_damage"] == km]
        brands = km_odometer["brand"].value_counts(normalize = True)
        represented_brands = brands[brands > .02].index
    
        price_mean_by_brand = {}
    
        for b in represented_brands:
            selected_rows = km_odometer[km_odometer["brand"] == b]
            mean = selected_rows["price"].mean()
            price_mean_by_brand[b] = int(mean)
        
        new_series = pd.Series(price_mean_by_brand)
        if km == "yes":
            new_database = pd.DataFrame(new_series, columns=[km])
        elif km != "not_specified":
            new_database[km] = new_series
        else:
            new_database[km] = new_series
                        
    return new_database

In [62]:
brands_by_damage = mean_analysis(unrepaired_damage)
brands_by_damage

                yes       no  not_specified
audi           3430  10904.0         5236.0
bmw            3701   9384.0         5258.0
fiat           1488   3530.0         2081.0
ford           1657   4516.0         2202.0
mercedes_benz  4033   9585.0         5232.0
nissan         2256      NaN            NaN
opel           1646   3747.0         2014.0
peugeot        1649   3723.0         2223.0
renault        1383   3187.0         1530.0
volkswagen     2409   6553.0         3285.0

According to the above analysis, cars with unspecified damage lose almost half the value of cars that report have no damage. Cars with unrepaired damage have value slightly below that of cars with unspecified damage.
It's safe to say that cars with unspecified damage do have unrepaired damage.

## 10.- Closing commentary

These are my findings after reviewing *eBay Kelinanzeigen* data and doing simple analysis:

* Decided to drop 10% of the data, because either it was outliers or it was not realistic.
* Cars are sold at a continous pace. It would help my analysis to have data of a complete year to see how seasons affect transactions.
* German cars tend to sell for more, as Audi, BMW, Mercedes Benz and Volkswagen are in the top positions.
* The average mileage for the cars in the data was 125,000
* Data from name column was not easy to interpret, an was left as-is.
* The most common brand/model combinations are German cars, mainly Volkswagen.
* Cars begin to lose value faster after they reach 30,000 to 50,000 km.
* Cars that either have damage or is not specified tend to have less than have the value of cars without it.


Take aways:

* If one wants to buy a car, it's better to buy them if they have more than 50,000 km.
* If one wants to sell a car, it's better to sell it before it reaches 30,000 km.
* It's better to buy a German car, as it's value remains constant throughout time and have a high resale value.
* It's better to repair damages or risk losing half of the car's value.